version: '3'
services:
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: admin
        networks:
            - app-tier
        volumes:
            - ./mongo:/docker-entrypoint-initdb.d
    
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin
        depends_on:
            - mongo
        networks:
            - app-tier
        ports:
            - 8081:8081
        volumes:
            - ./.docker/mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh

    flask:
        container_name: flask
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mongo
        networks:
            - app-tier
        command:
            tail -f /dev/null

    solr:
        container_name: solr
        image: solr:8
        ports:
            - "8983:8983"
        volumes:
            - ./.docker/solr/docker-entrypoint.sh
        command:
            - solr-precreate
            - gettingstarted

networks:
    app-tier:
        driver: bridge